name: viva_wallet_pos
description: This is a flutter plugin for Android integration with Viva Wallet POS.
version: 0.0.8+2
homepage: https://github.com/drigler/viva_wallet_pos


environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: hr.drigler.viva_wallet_pos
        pluginClass: VivaWalletPosPlugin


topics:
  - payment
  - checkout
  - pos
  - ecommerce
